/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PlaylistMusik.Bab8;

import PlaylistMusik.Bab7.*;

/**
 *
 * @author Berlian
 */
public class GUI_MenuPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MenuPlaylist
     */
    public GUI_MenuPlaylist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        GUI_PlaylistMusik = new javax.swing.JMenuItem();
        GUI_PlaylistFavorite = new javax.swing.JMenuItem();
        GUI_TambahPlaylist = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROGRAM MENU PLAYLIST");

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        GUI_PlaylistMusik.setText("GUI PlaylistMusik");
        GUI_PlaylistMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_PlaylistMusikActionPerformed(evt);
            }
        });
        jMenu2.add(GUI_PlaylistMusik);

        GUI_PlaylistFavorite.setText("GUI PlaylistFavorite");
        GUI_PlaylistFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_PlaylistFavoriteActionPerformed(evt);
            }
        });
        jMenu2.add(GUI_PlaylistFavorite);

        GUI_TambahPlaylist.setText("GUI TambahPlaylist");
        GUI_TambahPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_TambahPlaylistActionPerformed(evt);
            }
        });
        jMenu2.add(GUI_TambahPlaylist);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUI_PlaylistFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_PlaylistFavoriteActionPerformed
        // TODO add your handling code here:
        GUI_PlaylistFavorite favorite = new GUI_PlaylistFavorite();
        favorite.show();
    }//GEN-LAST:event_GUI_PlaylistFavoriteActionPerformed

    private void GUI_PlaylistMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_PlaylistMusikActionPerformed
        // TODO add your handling code here:
        GUI_PlaylistMusik playlist = new GUI_PlaylistMusik();
        playlist.show();
    }//GEN-LAST:event_GUI_PlaylistMusikActionPerformed

    private void GUI_TambahPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_TambahPlaylistActionPerformed
        // TODO add your handling code here:
        GUI_TambahPlaylist tplaylist = new GUI_TambahPlaylist();
        tplaylist.show();
    }//GEN-LAST:event_GUI_TambahPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MenuPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GUI_PlaylistFavorite;
    private javax.swing.JMenuItem GUI_PlaylistMusik;
    private javax.swing.JMenuItem GUI_TambahPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
